### ISSUE TITLE
Discuss sudo requirement

### ISSUE THREAD

**Issue by fhaverkamp** [ibm-capi/capi-utils#13]
Hi Kenneth,

in our automatic regression test environment, I like to avoid sudo. In some cases I do ssh ... and that in particular does not really like those sudo operations. Do you see a way to get around the need for sudo in your update script? The lock is something it is currently needed for, but we could make the directory rw for normal users during install, maybe? Anything else needing sudo? Mhmmm. My new eeh setup ... brrr.

Regards

Frank

**Comment by mbrobbel** [comment]
If I remember correctly, root was required for two things;

1. `setpci` to query the PCI configuration space;
https://github.com/mbrobbel/capi-flash-script/blob/master/capi-flash-script.sh#L52
However, this has been replaced with a simple `cat`;
https://github.com/ibm-capi/capi-utils/blob/master/capi-flash-script.sh#L87

2. Resetting the card by writing to the PCI configuration space;
https://github.com/ibm-capi/capi-utils/blob/master/capi-flash-script.sh#L159#L160

The `/var/cxl/` root requirement should simply be fixed by changing the permissions of that directory with an init script.

**Comment by fhaverkamp** [comment]
@mbrobbel Who is creating the /var/cxl directory? I wonder about the reset and who should be allowed to do that.

**Comment by mbrobbel** [comment]
Regarding the `/var/cxl/` directory; 
https://github.com/ibm-capi/capi-utils/blob/master/capi-flash-script.sh#L55

Don't know about the reset.

**Comment by kenhill** [comment]
@fhaverkamp The script has evolved to primarily use the sysfs mount for cxl. We could replace the sudo requirement with group permissions (I add a `cxl` group to my development boxes). 

One motivation to keep sudo was to force the user to acknowledge that they want to change the state of the card. I think this can be relaxed if the fall back mechanism to the factory image is working properly. Otherwise, we may want to keep sudo a little longer.

**Comment by fhaverkamp** [comment]
@kenhill The cxl group stuff I do not really like. This imposes requirements on the user which needs to create the group, log in and out etc. I have that with CAPI GZIP at the moment and it is really not convenient and I do not really see the benefit. For the test-setup the cxl setup is probably ok. Are you implying taht the fallback mechanism is not really working? I mean, I think flashing the other side is even missing in the published version, which is something we should discuss too. SNAP users potentially like to update the card once in a while and a working fallback mechanism, is a good thing to have in those cases. With the opportunity of course to exchange the golden image if needed.

**Comment by kenhill** [comment]
@fhaverkamp I plan to rewrite the flashing code to directly use the PCI config space mount on sysfs. To my understanding, root/sudo permissions is required to write to the flash registers in VSEC.

**Comment by bmesnet** [comment]
Answered in issue #44
